# **Quiz 1 — Linear Algebra**



## Q1. (3 marks) For a = [3, −4] and b = [2, 1], compute:
(a) a · b

(b) |a|₂

(c) |a|₁




In [6]:
import numpy as np

a= np.array([3,-4])
b= np.array([2,1])

print(f"Vector a: {a}")
print(f"Vector b: {b}")

Vector a: [ 3 -4]
Vector b: [2 1]


#### (a) Compute a.b

In [14]:
# (a) a.b
dot_product = a@b
print(f"Dot product of a and b: {dot_product}")

#In this case, since a.b = 2 > (0), so the vectors have an acute angle between them

Dot product of a and b: 2


#### (b) Compute |a|₂ (L2 Norm / Euclidean Norm)

In [15]:
# Compute the L2 norm of vector a
l2_norm_a = np.linalg.norm(a)

print(f"|a|₂ = {l2_norm_a}")

|a|₂ = 5.0


#### (c) Compute |a|₁ (L1 Norm / Manhattan Norm)

In [16]:
# Compute the L1 norm of vector a
l1_norm_a = np.linalg.norm(a, ord=1)

print(f"|a|₁ = {l1_norm_a}")

|a|₁ = 7.0


## **Q2. (2 marks)**

What does a dot product of **zero** tell you about two non-zero vectors?

Give the geometric meaning in one sentence.


# Answer:

A dot product of **zero** between two non-zero vectors means that their individual contributions **cancel each other out**, resulting in a net contribution of zero.

**Example:**

For two vectors:

a1 = [1, 1]  
b1 = [1, -1]

a1 · b1 = (1 × 1) + (1 × -1)  
        = 1 - 1  
        = 0

Here, the contributions **+1 and -1 cancel each other out**.

**Geometric meaning:** The two vectors are **perpendicular (orthogonal)** to each other

In [22]:
a1 = np.array([1,1])
b1 = np.array([1,-1])

# Compute the dot product of a1 and b1
dot_product_a1_b1 = a1@b1

print(f"Dot product of a1 and b1: {dot_product_a1_b1}")

Dot product of a1 and b1: 0


## **Q3. (3 marks)**

Using your answers from Q1, compute the cosine similarity of `a` and `b` to 3 decimal places.

`|b|₂ = √5 ≈ 2.236`


In [23]:
cosine_similarity = dot_product / (l2_norm_a * 2.236)

print(f"Cosine similarity of a and b: {cosine_similarity:.3f}")

Cosine similarity of a and b: 0.179


## **Q4. (2 marks)**

**Two document vectors have a large dot product but a cosine similarity near zero — is that possible? Explain in one sentence.**

### **Answer:**

**Yes, it is possible; for example, two vectors can have very large magnitudes that produce a large dot product while being nearly perpendicular, resulting in a cosine similarity close to zero.**

In [26]:
import numpy as np

vec1 = np.array([1000000, 0])
vec2 = np.array([1, 1000000])

print(f"Vector 1: {vec1}")
print(f"Vector 2: {vec2}")

dot_product_example = np.dot(vec1, vec2)

# L2 norms
norm_vec1 = np.linalg.norm(vec1)
norm_vec2 = np.linalg.norm(vec2)

# cosine similarity
cosine_similarity_example = dot_product_example / (norm_vec1 * norm_vec2)

print(f"\nDot product: {dot_product_example}")
print(f"Norm of Vector 1: {norm_vec1:.2f}")
print(f"Norm of Vector 2: {norm_vec2:.2f}")
print(f"Cosine similarity: {cosine_similarity_example:.4f}")

Vector 1: [1000000       0]
Vector 2: [      1 1000000]

Dot product: 1000000
Norm of Vector 1: 1000000.00
Norm of Vector 2: 1000000.00
Cosine similarity: 0.0000


## Q5. (4 marks)

For

A = \[[1 2], [3 4]]   
B = \[[0 1], [1 0]]

compute A @ B and B @ A. State in one sentence what the pair demonstrates.

In [27]:
import numpy as np

# Define matrices A and B
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[0, 1],
              [1, 0]])

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

Matrix A:
 [[1 2]
 [3 4]]

Matrix B:
 [[0 1]
 [1 0]]


### Compute A @ B

In [28]:
# Compute A @ B
result_AB = A @ B

print("Result of A @ B:\n", result_AB)

Result of A @ B:
 [[2 1]
 [4 3]]


### Compute B @ A

In [29]:
# Compute B @ A
result_BA = B @ A

print("Result of B @ A:\n", result_BA)

Result of B @ A:
 [[3 4]
 [1 2]]


### What the pair demonstrates:

The pair demonstrates that matrix multiplication is generally not commutative; that is, A @ B is not necessarily equal to B @ A.

## Q6. (3 marks) For each, say whether the operation succeeds and give the result shape, or write FAILS:

(a) (5,3) + (3,)
(b) (5,3) + (5,)
(c) (4,1) @ (1,4)

### (a) (5,3) + (3,)

In [30]:
import numpy as np

A_a = np.random.rand(5, 3)
B_a = np.random.rand(3,)

print(f"Shape of A_a: {A_a.shape}")
print(f"Shape of B_a: {B_a.shape}")

# Operation
result_a = A_a + B_a

print(f"Operation succeeds. Result shape: {result_a.shape}")

Shape of A_a: (5, 3)
Shape of B_a: (3,)
Operation succeeds. Result shape: (5, 3)


### (b) (5,3) + (5,)

In [31]:
import numpy as np

A_b = np.random.rand(5, 3)
B_b = np.random.rand(5,)

print(f"Shape of A_b: {A_b.shape}")
print(f"Shape of B_b: {B_b.shape}")

# Operation (expected to fail due to incompatible shapes for broadcasting)
try:
    result_b = A_b + B_b
    print(f"Operation succeeds. Result shape: {result_b.shape}")
except ValueError as e:
    print(f"Operation FAILS: {e}")

Shape of A_b: (5, 3)
Shape of B_b: (5,)
Operation FAILS: operands could not be broadcast together with shapes (5,3) (5,) 


### (c) (4,1) @ (1,4)

In [32]:
import numpy as np

A_c = np.random.rand(4, 1)
B_c = np.random.rand(1, 4)

print(f"Shape of A_c: {A_c.shape}")
print(f"Shape of B_c: {B_c.shape}")

# Operation (matrix multiplication)
result_c = A_c @ B_c

print(f"Operation succeeds. Result shape: {result_c.shape}")

Shape of A_c: (4, 1)
Shape of B_c: (1, 4)
Operation succeeds. Result shape: (4, 4)


## Q7. (2 marks) Compute the determinant of [[3, 1], [2, 4]], and say what a determinant of zero would have meant.

In [1]:
import numpy as np

matrix_q7 = np.array([[3, 1],
                      [2, 4]])

determinant = np.linalg.det(matrix_q7)

print(f"Matrix:\n{matrix_q7}")
print(f"Determinant: {determinant:.2f}")

Matrix:
[[3 1]
 [2 4]]
Determinant: 10.00


### Meaning of a zero determinant:

A determinant of zero for a square matrix means that the matrix transformation has lost information/dimension. Geometrically, for a 2D matrix, this means the transformation maps shapes to a line or a point (collapsing the area to zero); for a 3D matrix, it maps volumes to a plane, line, or point (collapsing the volume to zero).

## Q8. (4 marks) Find the eigenvalues of

M = [[5  2]
     [2  2]]
by solving the characteristic equation. Show the equation you formed.

To find the eigenvalues, we need to solve the characteristic equation, which is given by $\det(M - \lambda I) = 0$, where $M$ is the given matrix, $\lambda$ represents the eigenvalues, and $I$ is the identity matrix.

For the given matrix $M = \begin{pmatrix} 5 & 2 \\ 2 & 2 \end{pmatrix}$ and the identity matrix $I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix}$, we have:

$M - \lambda I = \begin{pmatrix} 5 & 2 \\ 2 & 2 \end{pmatrix} - \lambda \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} = \begin{pmatrix} 5-\lambda & 2 \\ 2 & 2-\lambda \end{pmatrix}$

The determinant is then:

$\det(M - \lambda I) = (5-\lambda)(2-\lambda) - (2)(2) = 0$

Expanding this, we get:

$10 - 5\lambda - 2\lambda + \lambda^2 - 4 = 0$

$\lambda^2 - 7\lambda + 6 = 0$

This is the characteristic equation. We can solve this quadratic equation for $\lambda$.

In [2]:
import numpy as np

M = np.array([[5, 2],
              [2, 2]])

# Calculate eigenvalues using numpy
eigenvalues = np.linalg.eigvals(M)

print(f"Matrix M:\n{M}")
print(f"Eigenvalues: {eigenvalues}")

# We can also solve the characteristic equation analytically:
# lambda^2 - 7*lambda + 6 = 0
# (lambda - 6)(lambda - 1) = 0
# So, lambda = 6 or lambda = 1

Matrix M:
[[5 2]
 [2 2]]
Eigenvalues: [6. 1.]


## Q9. (1 mark) X is (200, 8). What is the shape of Xᵀ X?

To determine the shape of $X^T X$, we need to recall the rules for matrix multiplication and transposition.

1.  **Shape of $X$:** Given as $(200, 8)$.
2.  **Shape of $X^T$ (X transpose):** If $X$ is $(m, n)$, then $X^T$ is $(n, m)$. So, if $X$ is $(200, 8)$, then $X^T$ is $(8, 200)$.
3.  **Shape of $X^T X$:** For matrix multiplication $A \times B$, if $A$ has shape $(m, n)$ and $B$ has shape $(n, p)$, the resulting matrix $A \times B$ has shape $(m, p)$.

    In our case, $A = X^T$ and $B = X$.
    *   Shape of $X^T$: $(8, 200)$
    *   Shape of $X$: $(200, 8)$

    The inner dimensions match (200), so the multiplication is valid. The resulting shape will be the outer dimensions: $(8, 8)$.

**Answer:** The shape of $X^T X$ is $(8, 8)$.

In [3]:
import numpy as np

# Create a dummy array X with shape (200, 8)
X = np.random.rand(200, 8)

print(f"Shape of X: {X.shape}")

# Compute X transpose X
XTX = X.T @ X

print(f"Shape of X.T: {X.T.shape}")
print(f"Shape of X.T @ X: {XTX.shape}")

Shape of X: (200, 8)
Shape of X.T: (8, 200)
Shape of X.T @ X: (8, 8)


## Q10. (1 mark) In one sentence: why should you write `np.linalg.solve(A, b)` rather than `np.linalg.inv(A) @ b`?

**Answer:** `np.linalg.solve(A, b)` is numerically more stable and computationally more efficient than `np.linalg.inv(A) @ b` because it directly solves the linear system without explicitly calculating the inverse of A, which can introduce precision errors and be more costly for large matrices.